# Node selector example which only picks the node
apiVersion: v1
kind: Pod
metadata:
  name: node-selector
spec:
  containers:
  - image: k8spatterns/random-generator:1.0
    name: random-generator
  nodeSelector:
    # Simple match on labels
    disktype: ssd
