apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    run: fileserver
  name: fileserver
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      run: fileserver
  template:
    metadata:
      labels:
        run: fileserver
    spec:
      containers:
      - image: richardchesterwood/k8s-fleetman-webapp-angular:release0
        imagePullPolicy: Always
        name: fileserver
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        resources:
          requests:
            memory: 300Mi
            cpu: 100m
          limits:
            memory: 300Mi
            cpu: 100m
      dnsPolicy: ClusterFirst
      restartPolicy: Always


