# Tolerations
---
apiVersion: v1
kind: Pod
metadata:
  name: tolerations
spec:
  containers:
  - image: k8spatterns/random-generator:1.0
    name: random-generator
  tolerations:
  - key: node-role.kubernetes.io/master
    operator: Exists
    effect: NoSchedule
