apiVersion: v1
kind: ConfigMap
metadata:
  name: global-database-config-v3
  namespace: default
data:
  database-properties: |
    database-url= "https://changed.somewhere.com:3306/"
    database-password= "password"

