kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: visitors-helm-chartops
subjects:
- kind: ServiceAccount
  name: visitors-helm-chartops
roleRef:
  kind: Role
  name: visitors-helm-chartops
  apiGroup: rbac.authorization.k8s.io
